//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class EasyRepro : global::System.Configuration.ApplicationSettingsBase {
        
        private static EasyRepro defaultInstance = ((EasyRepro)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EasyRepro())));
        
        public static EasyRepro Default {
            get {
                return defaultInstance;
            }
        }
    }
}
